### ISSUE TITLE
Making it official package?

### ISSUE THREAD

**Issue by heeh** [vcprocles/aegisub-procles-snap#6]
This is HUGE! Is there any plan to make it official?

**Comment by vcprocles** [comment]
Hi. I doubt this is really possible, since Aegisub is basically a dead project. The last commit to the [original repository](https://github.com/Aegisub/Aegisub) was in 2019, and the last official release was all the way back in 2014. Even the official website was dead at the moment of creating this package. (recently they resurrected it, mayhaps the project is going to see some activity soon?)
The original version doesn't even build on modern Linux systems without patching, I might've needed to use the Ubuntu 16.04 runtime to make that work without much intervention.

Because of that, I use the already [unofficial fork](https://github.com/wangqr/Aegisub) that has all the patches for smoother use and build on the modern systems. 

Maybe later if the original project resurrects, or some kind of big fork appears, I will look into making this package official. And also before that I need to figure out how to fix the version number being a commit ID.
